version: '3.6'

networks:
  james-server:
    driver: bridge

services:
  james-api:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - DB_HOST=james-postgres
    depends_on:
      - james-postgres
    networks:
      - james-server
    container_name: james-api
    command: yarn dev
    ports:
      - '3333:3333'

  james-postgres:
    image: postgres
    container_name: james-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    networks:
      - james-server

  